name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: install
      run: yarn install

    - name: test
      run: yarn test && yarn test

    - name: build
      run: npm run build

    - name: deploy
      run: |
        git config --global user.email homutovan@live.com
        git config --global user.name "Git Actions"
        push-dir --dir=dist --branch=deploy --force --verbose
